fix(scaleSelector): error when uiMachineOptions missing scaleSelector
If custom config does not include uiMachineOptions.images.services.scaleSelector
there is an state machine error:
Error: Unable to send event to child 'scaleSelector' from service 'images'.

This change provides default stub for the scaleSelector

closes #516